#############################################################################
# Makefile for building: Indexing
# Generated by qmake (2.01a) (Qt 4.7.1) on: Sun Dec 5 19:44:58 2010
# Project:  Indexing.pro
# Template: app
# Command: /home/Qt/Qt4.7.1/bin/qmake -spec /usr/local/Trolltech/Qt-4.7.1/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/Qt/qt-creator-2.1.0-rc1-src/share/qtcreator/qml/qmljsdebugger -o Makefile Indexing.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.1/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.1/include/QtCore -I/usr/local/Trolltech/Qt-4.7.1/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.1/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.1/lib -lQtCore -L/usr/local/Trolltech/Qt-4.7.1/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/Qt/Qt4.7.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cforwardindex.cpp \
		cinvertedindex.cpp \
		globalData.cpp 
OBJECTS       = main.o \
		cforwardindex.o \
		cinvertedindex.o \
		globalData.o
DIST          = /usr/local/Trolltech/Qt-4.7.1/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/include_source_dir.prf \
		Indexing.pro
QMAKE_TARGET  = Indexing
DESTDIR       = 
TARGET        = Indexing

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Indexing.pro  /usr/local/Trolltech/Qt-4.7.1/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.1/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.1/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.1/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/Qt/qt-creator-2.1.0-rc1-src/share/qtcreator/qml/qmljsdebugger -o Makefile Indexing.pro
/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.1/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.1/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/Qt/qt-creator-2.1.0-rc1-src/share/qtcreator/qml/qmljsdebugger -o Makefile Indexing.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Indexing1.0.0 || $(MKDIR) .tmp/Indexing1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Indexing1.0.0/ && $(COPY_FILE) --parents cforwardindex.h cinvertedindex.h globalData.h .tmp/Indexing1.0.0/ && $(COPY_FILE) --parents main.cpp cforwardindex.cpp cinvertedindex.cpp globalData.cpp .tmp/Indexing1.0.0/ && (cd `dirname .tmp/Indexing1.0.0` && $(TAR) Indexing1.0.0.tar Indexing1.0.0 && $(COMPRESS) Indexing1.0.0.tar) && $(MOVE) `dirname .tmp/Indexing1.0.0`/Indexing1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Indexing1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp cforwardindex.h \
		globalData.h \
		cinvertedindex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cforwardindex.o: cforwardindex.cpp cforwardindex.h \
		globalData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cforwardindex.o cforwardindex.cpp

cinvertedindex.o: cinvertedindex.cpp cinvertedindex.h \
		globalData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cinvertedindex.o cinvertedindex.cpp

globalData.o: globalData.cpp globalData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globalData.o globalData.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

